"""
Pre-Commit Validator - Git Hook for Wellness Checks

Validates code before commits to ensure all changes meet wellness standards.
Prevents anti-patterns and stress-inducing code from entering the codebase.
"""

import os
import sys
import json
import subprocess
import logging
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple
from dataclasses import dataclass

from ..validation.wellness_code_validator import WellnessCodeValidator, WellnessViolation

logger = logging.getLogger(__name__)


@dataclass
class CommitValidationResult:
    """Result of pre-commit validation"""
    passed: bool
    violations: List[WellnessViolation]
    files_checked: List[str]
    wellness_score: float
    message: str


class PreCommitValidator:
    """
    Git pre-commit hook validator for wellness-aware development.
    
    Installation:
        1. Copy to .git/hooks/pre-commit
        2. Make executable: chmod +x .git/hooks/pre-commit
        3. Or use: pollen install-hook
    
    Behavior:
        - Blocks commits with critical wellness violations
        - Warns on minor violations
        - Calculates wellness score for the commit
        - Logs to Terracare ledger (optional)
    """
    
    HOOK_TEMPLATE = '''#!/bin/sh
# Pollen Pre-Commit Hook - Healing-Centric Development
# Auto-generated by Pollen

echo "Running Pollen wellness checks..."

# Run Python validator
python -m pollen.ide_integration.pre_commit_validator "$@"

# Exit with Python's exit code
exit $?
'''
    
    def __init__(self, 
                 block_on_critical: bool = True,
                 warn_on_warnings: bool = True,
                 min_wellness_score: float = 6.0):
        self.validator = WellnessCodeValidator()
        self.block_on_critical = block_on_critical
        self.warn_on_warnings = warn_on_warnings
        self.min_wellness_score = min_wellness_score
        
    def install_hook(self, repo_path: str = '.') -> bool:
        """
        Install the pre-commit hook in the git repository.
        
        Args:
            repo_path: Path to git repository
            
        Returns:
            True if installed successfully
        """
        git_dir = Path(repo_path) / '.git'
        if not git_dir.exists():
            logger.error(f"Not a git repository: {repo_path}")
            return False
        
        hook_path = git_dir / 'hooks' / 'pre-commit'
        
        try:
            # Write hook script
            hook_path.write_text(self.HOOK_TEMPLATE)
            
            # Make executable (Unix)
            if os.name != 'nt':
                hook_path.chmod(0o755)
            
            logger.info(f"Installed pre-commit hook at {hook_path}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to install hook: {e}")
            return False
    
    def validate_staged_files(self, repo_path: str = '.') -> CommitValidationResult:
        """
        Validate all staged files before commit.
        
        Args:
            repo_path: Path to git repository
            
        Returns:
            CommitValidationResult with validation status
        """
        # Get staged files
        staged_files = self._get_staged_files(repo_path)
        
        if not staged_files:
            return CommitValidationResult(
                passed=True,
                violations=[],
                files_checked=[],
                wellness_score=10.0,
                message="No staged files to check"
            )
        
        all_violations = []
        total_score = 0.0
        
        for file_path in staged_files:
            # Only check code files
            if not self._is_code_file(file_path):
                continue
            
            # Get file diff
            diff = self._get_file_diff(file_path, repo_path)
            
            if not diff:
                continue
            
            # Validate
            is_valid, violations, metadata = self.validator.validate_edit(
                diff,
                biometric_context={'hrv': 50, 'sleep_score': 7}  # Default for commit
            )
            
            all_violations.extend(violations)
            
            # Calculate score
            if metadata.get('cognitive_load_report'):
                load = metadata['cognitive_load_report'].overall_score
                file_score = max(0, 10 - load)
                total_score += file_score
        
        # Average score
        avg_score = total_score / len(staged_files) if staged_files else 10.0
        
        # Determine if commit should pass
        critical_count = len([v for v in all_violations if v.severity == 'critical'])
        
        passed = True
        messages = []
        
        if critical_count > 0 and self.block_on_critical:
            passed = False
            messages.append(f"Commit blocked: {critical_count} critical wellness violations")
        
        if avg_score < self.min_wellness_score:
            passed = False
            messages.append(f"Commit blocked: Wellness score {avg_score:.1f} below minimum {self.min_wellness_score}")
        
        if not passed:
            messages.append("\\nTo bypass (not recommended): git commit --no-verify")
        
        return CommitValidationResult(
            passed=passed,
            violations=all_violations,
            files_checked=staged_files,
            wellness_score=avg_score,
            message="\\n".join(messages) if messages else "All wellness checks passed"
        )
    
    def _get_staged_files(self, repo_path: str) -> List[str]:
        """Get list of staged files"""
        try:
            result = subprocess.run(
                ['git', 'diff', '--cached', '--name-only'],
                cwd=repo_path,
                capture_output=True,
                text=True
            )
            return [f.strip() for f in result.stdout.split('\\n') if f.strip()]
        except Exception as e:
            logger.error(f"Failed to get staged files: {e}")
            return []
    
    def _get_file_diff(self, file_path: str, repo_path: str) -> str:
        """Get diff for a staged file"""
        try:
            result = subprocess.run(
                ['git', 'diff', '--cached', file_path],
                cwd=repo_path,
                capture_output=True,
                text=True
            )
            return result.stdout
        except Exception as e:
            logger.error(f"Failed to get diff for {file_path}: {e}")
            return ""
    
    def _is_code_file(self, file_path: str) -> bool:
        """Check if file is a code file we should validate"""
        code_extensions = {
            '.py', '.js', '.jsx', '.ts', '.tsx',
            '.html', '.css', '.scss', '.sass',
            '.java', '.kt', '.swift',
            '.go', '.rs', '.cpp', '.c', '.h',
        }
        ext = Path(file_path).suffix.lower()
        return ext in code_extensions
    
    def print_report(self, result: CommitValidationResult):
        """Print validation report to console"""
        print("\\n" + "=" * 60)
        print("🌸 POLLEN WELLNESS COMMIT REPORT")
        print("=" * 60)
        
        print(f"\\nFiles checked: {len(result.files_checked)}")
        for f in result.files_checked:
            print(f"  - {f}")
        
        print(f"\\nWellness score: {result.wellness_score:.1f}/10.0")
        
        if result.violations:
            print(f"\\nViolations found: {len(result.violations)}")
            
            by_severity = {}
            for v in result.violations:
                by_severity.setdefault(v.severity, []).append(v)
            
            for severity in ['critical', 'warning', 'info']:
                if severity in by_severity:
                    print(f"\\n  {severity.upper()}:")
                    for v in by_severity[severity]:
                        print(f"    - {v.message}")
        else:
            print("\\n✅ No wellness violations found")
        
        print("\\n" + "=" * 60)
        print(result.message)
        print("=" * 60 + "\\n")


def main():
    """Main entry point for git hook"""
    validator = PreCommitValidator()
    
    # Check if running as hook or manual
    if len(sys.argv) > 1 and sys.argv[1] == '--install':
        # Install mode
        success = validator.install_hook()
        sys.exit(0 if success else 1)
    
    # Validation mode
    result = validator.validate_staged_files()
    validator.print_report(result)
    
    sys.exit(0 if result.passed else 1)


if __name__ == '__main__':
    main()
